#!/usr/bin/env bash
# PorterClaude — the four generic agent installers. OWNER: O1. v0.2.
# Spec: docs/design/orchestration.md §13.6, §13.7, §13.9.
#
# CONTRACT (identical for every function here and for every per-agent override):
#   in : $AGENT_ID $AGENT_COMMAND $AGENT_DIR (exists, empty) $AGENT_SPEC (JSON object)
#        $TOOLS_MOUNT (= the runtime path, /opt/porterclaude) $ARCH ($TARGET)
#   out: 0  -> $AGENT_DIR/run.sh exists, is 0755 and execs the agent
#        >0 -> the reason was printed to stderr; the driver records installed:false
#   never: exit the caller, write outside $AGENT_DIR and $TOOLS_MOUNT/runtime, prompt, or
#          bake a `/out` path into anything (§13.2 — install through $TOOLS_MOUNT only).
#
# All four end by calling pc_write_run_sh, which is what guarantees the launcher shape.
set -uo pipefail

# pc_write_run_sh <exec-line> [<prelude>] : write $AGENT_DIR/run.sh (POSIX sh, 0755).
# <exec-line> is already-quoted shell that ends in `"$@"`; <prelude> is optional shell that
# runs before it (libc guards, binary dispatch). The generated file resolves its own
# directory ($AGENT_DIR) and $TOOLS from $0, so the payload stays relocatable and contains
# no `/out` path.
pc_write_run_sh() {
  local exec_line="$1" prelude="${2:-}"
  {
    printf '%s\n' '#!/bin/sh'
    printf '# PorterClaude launcher for the agent %s (generated by install-agents.sh). POSIX sh.\n' "$AGENT_ID"
    printf '%s\n' 'set -u'
    printf '%s\n' "CDPATH=''"
    printf '%s\n' 'AGENT_DIR="$(cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)"'
    printf '%s\n' '[ -n "$AGENT_DIR" ] || AGENT_DIR="$(dirname -- "$0")"'
    printf '%s\n' 'TOOLS="${PORTERCLAUDE_TOOLS:-}"'
    printf '%s\n' 'if [ -z "$TOOLS" ]; then'
    printf '%s\n' '  TOOLS="$(cd -- "$AGENT_DIR/../.." 2>/dev/null && pwd)"'
    printf '%s\n' '  [ -n "$TOOLS" ] || TOOLS=/opt/porterclaude'
    printf '%s\n' 'fi'
    printf '%s\n' 'PORTERCLAUDE_TOOLS="$TOOLS"; export PORTERCLAUDE_TOOLS'
    printf 'PC_AGENT_ID=%s\n' "$(pc_sh_quote "$AGENT_ID")"
    printf '%s\n' 'pc_is_musl() {'
    printf '%s\n' '  ls /lib/ld-musl-* >/dev/null 2>&1 && return 0'
    printf '%s\n' '  ldd --version 2>&1 | grep -qi musl && return 0'
    printf '%s\n' '  return 1'
    printf '%s\n' '}'
    printf '%s\n' 'pc_machine() {'
    printf '%s\n' '  case "$(uname -m 2>/dev/null || echo)" in'
    printf '%s\n' "    x86*64|amd64)          printf 'x64' ;;"
    printf '%s\n' "    aarch*64|arm64|armv8*) printf 'arm64' ;;"
    printf '%s\n' "    *)                     printf '' ;;"
    printf '%s\n' '  esac'
    printf '%s\n' '}'
    if [ -n "$prelude" ]; then
      printf '%s\n' "$prelude"
    fi
    printf '%s\n' "$exec_line"
  } | pc_write_exec "$AGENT_DIR/run.sh"
}

# pc_write_dispatch_run_sh <relative-dir> <prefix> : run.sh for an agent that ships NATIVE
# binaries named `<prefix>linux-<arch>` and (optionally) `<prefix>linux-<arch>-musl` inside
# $AGENT_DIR/<relative-dir>. Used by kind=binary and by the claude override — the v0.1
# dispatcher rule: a musl session needs the musl build, a glibc session prefers the plain
# build and falls back to the (statically linked) musl one.
pc_write_dispatch_run_sh() {
  local reldir="$1" prefix="$2" prelude
  prelude="$(
    printf 'PC_BIN_DIR="$AGENT_DIR"/%s\n' "$(pc_sh_quote "$reldir")"
    printf 'PC_PREFIX=%s\n' "$(pc_sh_quote "$prefix")"
    cat <<'DISPATCH'
_arch="$(pc_machine)"
if [ -z "$_arch" ]; then
  echo "porterclaude: $PC_AGENT_ID has no binary for architecture $(uname -m)" >&2
  exit 1
fi
_suffix=''
if pc_is_musl; then _suffix='-musl'; fi
_bin="$PC_BIN_DIR/${PC_PREFIX}linux-$_arch$_suffix"
if [ ! -x "$_bin" ]; then
  # the musl build is statically linked, so it also runs on glibc systems
  _alt="$PC_BIN_DIR/${PC_PREFIX}linux-$_arch-musl"
  if [ -z "$_suffix" ] && [ -x "$_alt" ]; then
    _bin="$_alt"
  else
    echo "porterclaude: $PC_AGENT_ID has no build for this container ($_arch, libc: ${_suffix:-glibc})." >&2
    echo "porterclaude: re-run Settings -> Images -> Sync tools." >&2
    exit 1
  fi
fi
DISPATCH
  )"
  pc_write_run_sh 'exec "$_bin" "$@"' "$prelude"
}

# pc_install_env : the `install.env` object as a KEY=VALUE list, one per line. Keys that are
# not plain identifiers are dropped — the definition is admin-supplied, but it must never be
# able to smuggle something into the installer's argv or into a generated script.
pc_install_env() {
  printf '%s' "$AGENT_SPEC" \
    | jq -r '(.install.env // {}) | to_entries[]
             | select(.key | test("^[A-Za-z_][A-Za-z0-9_]*$"))
             | "\(.key)=\(.value)"' 2>/dev/null || printf ''
}

# pc_script_interpreter <file> : the shell a downloaded installer must run under.
# QA B-4: running every `kind:script` installer with `sh` breaks on debian/ubuntu, where /bin/sh
# is dash — opencode's installer (https://opencode.ai/install) starts with `set -o pipefail` and
# dies with "Illegal option -o pipefail", so the agent could never be installed. The tools image
# ships bash, which also runs the POSIX-sh installers (claude's), so bash is the default; an
# explicit shebang asking for something else (and present in the image) still wins, and sh is
# only used when there is no bash at all.
pc_script_interpreter() {
  local file="$1" first want
  first="$(head -n 1 "$file" 2>/dev/null | tr -d '\r')"
  want=''
  case "$first" in
    '#!'*)
      want="$(printf '%s' "${first#\#!}" | awk '{ if ($1 ~ /(^|\/)env$/) print $2; else print $1 }')"
      want="${want##*/}"
      ;;
  esac
  case "$want" in
    zsh|ksh|mksh) command -v "$want" >/dev/null 2>&1 && { printf '%s' "$want"; return 0; } ;;
  esac
  command -v bash >/dev/null 2>&1 && { printf 'bash'; return 0; }
  printf 'sh'
}

# kind=script — curl the installer and run it (pc_script_interpreter, bash by default)
# with HOME/PREFIX pointed at
# $AGENT_DIR. `binPath` is a HINT: look for $AGENT_DIR/$binPath, then
# $AGENT_DIR/.local/$binPath, then `find $AGENT_DIR -type f -name "$AGENT_COMMAND" -perm -u+x`.
# `install.env` is exported for the installer run only. Multi-libc coverage is best effort
# for this kind (§13.7) — an agent that needs more ships an override in agents/<id>.sh.
pc_install_script() {
  local url bin_path tmp installer found rel runner
  local -a args=() envs=()
  url="$(pc_json_get "$AGENT_SPEC" '.install.url')"
  if [ -z "$url" ]; then
    echo "install.url is missing" >&2
    return 1
  fi
  bin_path="$(pc_json_get "$AGENT_SPEC" '.install.binPath')"
  [ -n "$bin_path" ] || bin_path="bin/$AGENT_COMMAND"

  # tr: jq on a non-unix host may emit CRLF, and a stray CR inside an argv element is
  # invisible in a log but changes the meaning of the argument
  mapfile -t args < <(printf '%s' "$AGENT_SPEC" | jq -r '.install.args[]? // empty' 2>/dev/null | tr -d '\r')
  mapfile -t envs < <(pc_install_env | tr -d '\r')

  tmp="$(mktemp -d)"
  installer="$tmp/install.sh"
  if ! pc_fetch "$url" "$installer"; then
    echo "cannot download the installer: $url" >&2
    rm -rf "$tmp"
    return 1
  fi

  mkdir -p "$AGENT_DIR/.local/bin"
  runner="$(pc_script_interpreter "$installer")"
  pc_log "running the installer of '$AGENT_ID' with $runner, HOME=$AGENT_DIR"
  if ! ( cd "$AGENT_DIR" && env \
           HOME="$AGENT_DIR" \
           PREFIX="$AGENT_DIR" \
           XDG_DATA_HOME="$AGENT_DIR/.local/share" \
           XDG_CONFIG_HOME="$AGENT_DIR/.config" \
           XDG_CACHE_HOME="$AGENT_DIR/.cache" \
           ${envs[@]+"${envs[@]}"} \
           "$runner" "$installer" ${args[@]+"${args[@]}"} 2>&1 | sed 's/^/[tools] /' ); then
    echo "the installer of '$AGENT_ID' failed" >&2
    rm -rf "$tmp"
    return 1
  fi
  rm -rf "$tmp" "$AGENT_DIR/.cache"

  found=""
  for rel in "$bin_path" ".local/$bin_path" ".local/bin/$AGENT_COMMAND" "bin/$AGENT_COMMAND"; do
    if [ -f "$AGENT_DIR/$rel" ] && [ -x "$AGENT_DIR/$rel" ]; then
      found="$rel"
      break
    fi
  done
  if [ -z "$found" ]; then
    found="$(cd "$AGENT_DIR" && find . -type f -name "$AGENT_COMMAND" -perm -u+x 2>/dev/null \
             | head -n1 | sed 's|^\./||')"
  fi
  if [ -z "$found" ]; then
    echo "the installer produced no '$AGENT_COMMAND' executable below $AGENT_DIR" >&2
    return 1
  fi
  pc_log "'$AGENT_ID' installed: $found"
  pc_write_run_sh "exec \"\$AGENT_DIR\"/$(pc_sh_quote "$found") \"\$@\""
}

# kind=npm — needs the bundled Node runtime (pc_ensure_node). Install with the bundled npm
# into $AGENT_DIR, then resolve the package's bin entry from
# $AGENT_DIR/node_modules/<pkg>/package.json (`.bin` is a string or an object; `install.bin`
# names the wanted one, default $AGENT_COMMAND) and generate a run.sh that execs
#   "$TOOLS/runtime/node/bin/node" "$AGENT_DIR/node_modules/<pkg>/<binjs>" "$@"
# — never the npm-generated .bin symlink (its shebang is `/usr/bin/env node`, which does not
# exist in a session image).
pc_install_npm() {
  local pkg ver bin_name npm_cli pkg_dir bin_js rel
  pkg="$(pc_json_get "$AGENT_SPEC" '.install.package')"
  if [ -z "$pkg" ]; then
    echo "install.package is missing" >&2
    return 1
  fi
  ver="$(pc_json_get "$AGENT_SPEC" '.install.version')"
  [ -n "$ver" ] || ver="latest"
  bin_name="$(pc_json_get "$AGENT_SPEC" '.install.bin')"
  [ -n "$bin_name" ] || bin_name="$AGENT_COMMAND"

  # NOT `$(pc_ensure_node)`: the function also sets $PC_NODE_BIN, and a command substitution
  # would run it in a subshell where that assignment is lost
  if ! pc_ensure_node >/dev/null; then
    echo "the bundled node runtime could not be provisioned — no npm agent can be installed" >&2
    return 1
  fi
  npm_cli="$PC_NPM_CLI"

  mkdir -p "$AGENT_DIR"
  pc_log "npm install $pkg@$ver (node $PC_NODE_VERSION)"
  # `env` must wrap the COMMAND, not pc_run (a shell function): `env VAR=x pc_run …` would
  # look for an executable called pc_run.
  if ! pc_run "${PORTERCLAUDE_AGENT_TIMEOUT:-900}" \
         env HOME="$AGENT_DIR/.npm-home" \
             npm_config_cache="/tmp/pc-npm-cache" \
             npm_config_update_notifier=false \
             npm_config_fund=false \
             npm_config_audit=false \
             "$PC_NODE_BIN" "$npm_cli" install \
             --prefix "$AGENT_DIR" --no-audit --no-fund --omit=dev --loglevel=warn \
             "$pkg@$ver"; then
    echo "npm install $pkg@$ver failed" >&2
    return 1
  fi
  rm -rf "$AGENT_DIR/.npm-home"

  pkg_dir="$AGENT_DIR/node_modules/$pkg"
  if [ ! -f "$pkg_dir/package.json" ]; then
    echo "npm did not install $pkg into the agent directory" >&2
    return 1
  fi
  bin_js="$(jq -r --arg b "$bin_name" '
      (.bin
       | if type == "string" then .
         elif type == "object" then (.[$b] // (to_entries | .[0].value // empty))
         else empty end) // empty' "$pkg_dir/package.json" 2>/dev/null)"
  if [ -z "$bin_js" ]; then
    echo "the package $pkg declares no bin entry for '$bin_name'" >&2
    return 1
  fi
  rel="node_modules/$pkg/${bin_js#./}"
  if [ ! -f "$AGENT_DIR/$rel" ]; then
    echo "the package $pkg does not ship $rel" >&2
    return 1
  fi
  pc_log "'$AGENT_ID' installed: $rel"
  pc_write_run_sh \
    "exec \"\$TOOLS/runtime/node/bin/node\" \"\$AGENT_DIR\"/$(pc_sh_quote "$rel") \"\$@\""
}

# kind=pip — needs uv (pc_ensure_uv) and a managed CPython (pc_ensure_python), both installed
# through $TOOLS_MOUNT so every shebang uv bakes already points at the runtime path (§13.2).
# `install.preferUv:false` (or an unavailable uv) falls back to `python -m venv` + pip.
# musl sessions are NOT supported for this kind: run.sh detects musl and exits with
# "…requires a glibc image on this host" instead of a confusing loader error.
pc_install_pip() {
  local pkg ver bin_name prefer_uv uv py want rel real guard
  pkg="$(pc_json_get "$AGENT_SPEC" '.install.package')"
  if [ -z "$pkg" ]; then
    echo "install.package is missing" >&2
    return 1
  fi
  ver="$(pc_json_get "$AGENT_SPEC" '.install.version')"
  bin_name="$(pc_json_get "$AGENT_SPEC" '.install.bin')"
  [ -n "$bin_name" ] || bin_name="$AGENT_COMMAND"
  prefer_uv="$(pc_json_get "$AGENT_SPEC" '.install.preferUv')"
  [ -n "$prefer_uv" ] || prefer_uv="true"
  want="$pkg"
  [ -z "$ver" ] || want="$pkg==$ver"

  # the pc_ensure_* functions set globals as well as printing, so they are called directly
  # (a command substitution would lose the globals to a subshell)
  uv=""
  if [ "$prefer_uv" != "false" ] && pc_ensure_uv >/dev/null; then
    uv="$PC_UV_BIN"
  fi
  if ! pc_ensure_python >/dev/null; then
    echo "no python runtime could be provisioned — no pip agent can be installed" >&2
    return 1
  fi
  py="$PC_PYTHON_BIN"

  rel=""
  if [ -n "$uv" ]; then
    pc_log "uv tool install $want"
    if pc_run "${PORTERCLAUDE_AGENT_TIMEOUT:-900}" \
         env UV_TOOL_DIR="$AGENT_DIR/tools" \
             UV_TOOL_BIN_DIR="$AGENT_DIR/bin" \
             UV_PYTHON_INSTALL_DIR="$TOOLS_MOUNT/runtime/python" \
             UV_PYTHON_PREFERENCE=only-managed \
             HOME="$AGENT_DIR/.uv-home" \
             XDG_CACHE_HOME=/tmp/pc-uv-cache \
             "$uv" tool install --python "$PC_PYTHON_VERSION" "$want"; then
      if [ -e "$AGENT_DIR/bin/$bin_name" ]; then
        real="$(readlink -f "$AGENT_DIR/bin/$bin_name" 2>/dev/null || printf '')"
        case "$real" in
          "$AGENT_DIR"/*) rel="${real#"$AGENT_DIR"/}" ;;
          *)              rel="bin/$bin_name" ;;
        esac
      else
        rel="$(cd "$AGENT_DIR" && find tools -type f -name "$bin_name" -perm -u+x 2>/dev/null | head -n1)"
      fi
    else
      pc_warn "uv tool install $want failed — falling back to venv + pip"
    fi
    rm -rf "$AGENT_DIR/.uv-home"
  fi

  if [ -z "$rel" ]; then
    pc_log "python -m venv + pip install $want"
    rm -rf "$AGENT_DIR/venv"
    if ! pc_run 300 "$py" -m venv "$AGENT_DIR/venv"; then
      echo "could not create a virtualenv for $pkg" >&2
      return 1
    fi
    if ! pc_run "${PORTERCLAUDE_AGENT_TIMEOUT:-900}" \
           env HOME="$AGENT_DIR/.pip-home" PIP_DISABLE_PIP_VERSION_CHECK=1 \
               "$AGENT_DIR/venv/bin/python" -m pip install --no-cache-dir "$want"; then
      echo "pip install $want failed" >&2
      rm -rf "$AGENT_DIR/.pip-home"
      return 1
    fi
    rm -rf "$AGENT_DIR/.pip-home"
    if [ -x "$AGENT_DIR/venv/bin/$bin_name" ]; then
      rel="venv/bin/$bin_name"
    else
      echo "the package $pkg installed no '$bin_name' console script" >&2
      return 1
    fi
  fi

  # quoted heredoc: $PC_AGENT_ID stays literal here and is expanded by the generated script
  guard="$(cat <<'GUARD'
if pc_is_musl; then
  echo "porterclaude: $PC_AGENT_ID requires a glibc image on this host." >&2
  echo "porterclaude: python agents are not supported on musl (alpine) — use a debian or" >&2
  echo "porterclaude: ubuntu based image for this session." >&2
  exit 1
fi
GUARD
  )"
  pc_log "'$AGENT_ID' installed: $rel"
  pc_write_run_sh "exec \"\$AGENT_DIR\"/$(pc_sh_quote "$rel") \"\$@\"" "$guard"
}

# kind=binary — pick install.urls[$TARGET] (the glibc target first, then the -musl one;
# install BOTH when both are present so a musl session on this host is covered), download,
# verify it is executable, unpack when install.archive is tar.gz/zip and take install.path
# from inside. run.sh dispatches on the session's arch + libc.
pc_install_binary() {
  local archive inner_path arch suffix url tmp got flavour dest
  arch="$ARCH"
  if [ -z "$arch" ]; then
    echo "unsupported machine '$(uname -m)'" >&2
    return 1
  fi
  archive="$(pc_json_get "$AGENT_SPEC" '.install.archive')"
  [ -n "$archive" ] || archive="none"
  inner_path="$(pc_json_get "$AGENT_SPEC" '.install.path')"

  mkdir -p "$AGENT_DIR/bin"
  got=""
  for suffix in "" "-musl"; do
    flavour="linux-$arch$suffix"
    url="$(printf '%s' "$AGENT_SPEC" | jq -r --arg t "$flavour" '.install.urls[$t] // empty' 2>/dev/null)"
    [ -n "$url" ] || continue
    tmp="$(mktemp -d)"
    dest="$AGENT_DIR/bin/$AGENT_COMMAND-$flavour"
    pc_log "downloading $AGENT_ID ($flavour)"
    if ! pc_fetch "$url" "$tmp/download"; then
      pc_warn "$AGENT_ID: download failed for $flavour"
      rm -rf "$tmp"
      continue
    fi
    case "$archive" in
      none)
        mv -f "$tmp/download" "$dest"
        ;;
      tar.gz|zip)
        mv -f "$tmp/download" "$tmp/archive.$archive"
        if ! pc_extract "$tmp/archive.$archive" "$tmp/x" 0; then
          pc_warn "$AGENT_ID: cannot unpack the $flavour archive"
          rm -rf "$tmp"
          continue
        fi
        if [ -n "$inner_path" ] && [ -f "$tmp/x/$inner_path" ]; then
          mv -f "$tmp/x/$inner_path" "$dest"
        else
          inner="$(find "$tmp/x" -type f -name "$AGENT_COMMAND" -perm -u+x 2>/dev/null | head -n1)"
          if [ -z "$inner" ]; then
            pc_warn "$AGENT_ID: the $flavour archive carries no '$AGENT_COMMAND'"
            rm -rf "$tmp"
            continue
          fi
          mv -f "$inner" "$dest"
        fi
        ;;
      *)
        pc_warn "$AGENT_ID: unknown install.archive '$archive'"
        rm -rf "$tmp"
        continue
        ;;
    esac
    rm -rf "$tmp"
    chmod 0755 "$dest"
    got="$got $flavour"
  done

  if [ -z "$got" ]; then
    echo "no download URL for this host ($(pc_target 2>/dev/null || printf 'linux-%s' "$arch")) in install.urls" >&2
    return 1
  fi
  pc_log "'$AGENT_ID' installed:$got"
  pc_write_dispatch_run_sh "bin" "$AGENT_COMMAND-"
}
